version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install packages or any pre-reqs in this phase.
      - npm install serverless -g
      - sls --version

  # pre_build:
  #   commands:
  #   # Run tests, lint scripts or any other pre-build checks.
  #     - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd app
      - sls deploy

  # post_build:
  #   commands:
  #     # Use Post-Build for notifications, git tags, upload artifacts to S3
  #     - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - '**/*'
  base-directory: .serverless

# artifacts:
#   discard-paths: yes
#   files:
#     # List of local artifacts that will be passed down the pipeline
#     - sls-templated.yaml
